name: article-tta-codon
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10.0
  - pandas=2.0.0
  - matplotlib=3.7.1
  - scipy=1.10.1
  - pysam=0.21.0
  - biopython=1.81
  - ipykernel=6.22.0
